// Generated by ETERNAL_RESEARCH_CHILD/phase2_improvement_pipeline.ts
// Last refreshed: September 2026 (post Attached_Assets cleanup)
// Review before editing by hand.

export type ResearchImprovementKind =
  | "HARVEY_LAB_GUARDRAIL"
  | "CITATION_ACCURACY"
  | "PRECEDENT_REVIEW"
  | "STANDARD_REVIEW"
  | "DRAFTING_SAFETY"
  | "DEMO_ENRICHMENT"
  | "ROADMAP";

export type ResearchImprovementPriority = "P0" | "P1" | "P2";
export type ResearchImprovementStatus =
  | "READY_FOR_REVIEW"
  | "NEEDS_SOURCE_CHECK"
  | "BLOCKED_ACTIVE_MATTER";

export type ResearchImprovement = {
  id: string;
  title: string;
  kind: ResearchImprovementKind;
  priority: ResearchImprovementPriority;
  status: ResearchImprovementStatus;
  source: string;
  sourceType: "website" | "ebook" | "precedent" | "asset" | "log";
  targetArea: string;
  summary: string;
  reviewGate: string;
  labCriteria: string[];
};

export const RESEARCH_IMPROVEMENTS: ResearchImprovement[] = [
  {
    id: "harvey-lab-client-matter-workspace",
    title: "Harvey LAB guardrails for legal-agent work",
    kind: "HARVEY_LAB_GUARDRAIL",
    priority: "P0",
    status: "READY_FOR_REVIEW",
    source: "https://www.harvey.ai/blog/introducing-harveys-legal-agent-benchmark",
    sourceType: "website",
    targetArea: "improvement lab, review queue, and safe drafting",
    summary:
      "Use LAB concepts as a product rubric: closed matter workspace, reviewable work product, expert binary criteria, and all-pass grading.",
    reviewGate:
      "Generated work must remain a review artifact for counsel, not case-specific legal advice.",
    labCriteria: [
      "Matter materials are grouped before drafting.",
      "Output is reviewable work product.",
      "Every criterion is pass/fail.",
      "Task is complete only when all required criteria pass.",
    ],
  },
  {
    id: "citation-allowlist-enforcement",
    title: "Citation allowlist enforcement — auto-PENDING for unknown citations",
    kind: "CITATION_ACCURACY",
    priority: "P0",
    status: "READY_FOR_REVIEW",
    source: "ETERNAL_RESEARCH_CHILD/research_findings.log",
    sourceType: "log",
    targetArea: "src/lib/citation-gate.ts",
    summary:
      "Extend citation-gate.ts so any citation not matched in the registry with ≥ 2 tokens auto-escalates to BLOCKED (not WARN). Para-number references must also be blocked unless the para field is populated on the registry entry.",
    reviewGate:
      "Protected file — apply manually. Run pnpm typecheck + test after change.",
    labCriteria: [
      "Unknown citation not in registry → status BLOCKED.",
      "Para-number reference without populated para field → blocked from draft.",
      "All existing COURT_SAFE / VERIFIED citations continue to pass.",
      "citation-gate.test.ts suite stays green.",
    ],
  },
  {
    id: "precedent-structured-fields-remaining",
    title: "Populate reporter/volume/page/para on remaining VERIFIED precedents",
    kind: "PRECEDENT_REVIEW",
    priority: "P0",
    status: "NEEDS_SOURCE_CHECK",
    source: "artifacts/legal-luminaire/src/lib/case01-data.ts",
    sourceType: "asset",
    targetArea: "src/lib/case01-data.ts",
    summary:
      "Prafulla Kumar Samal (Para 10), Ramesh Singh (Para 5), Jacob Mathew (Para 48) have structured fields. Remaining VERIFIED entries — State of Maharashtra v. Damu (2000) 6 SCC 269, State of Punjab v. Baldev Singh (1999) 6 SCC 172, Kattavellai 2025 INSC 845, Surendra Koli (2025), Rajasthan HC PIL — need reporter/volume/page/para once certified copies obtained.",
    reviewGate:
      "Only populate para field from certified copy — never from secondary source summaries.",
    labCriteria: [
      "reporter, volume, page populated from citation string.",
      "para populated only after certified copy confirms paragraph.",
      "verifiedBy set to 'indiankanoon' or 'scc-online' as appropriate.",
      "No PENDING citation has para field populated.",
    ],
  },
  {
    id: "indian-kanoon-api-live-check",
    title: "Indian Kanoon API — live citation existence check",
    kind: "CITATION_ACCURACY",
    priority: "P0",
    status: "NEEDS_SOURCE_CHECK",
    source: "docs/roadmap/6_MONTH_ROADMAP.md",
    sourceType: "asset",
    targetArea: "src/lib/verification-engine.ts — Month 2 residual",
    summary:
      "Wire verifiedBy: 'indiankanoon' to a real API call: GET https://api.indiankanoon.org/search/?formInput=CASE_NAME. Mark VERIFIED only after API confirms existence. Failure falls back to SECONDARY. API key from environment variable.",
    reviewGate:
      "Requires INDIANKANOON_API_KEY env var. Add placeholder to .env.example. Never hardcode.",
    labCriteria: [
      "API call made on citation entry or verification trigger.",
      "Result stored in verifiedBy and sourceUrl fields.",
      "Failure (API unavailable) falls back to SECONDARY, not VERIFIED.",
      "API key loaded from environment variable.",
    ],
  },
  {
    id: "infra-arb-data-enrichment",
    title: "Enrich TC-22 to TC-26 data from real_cases/ source files",
    kind: "DEMO_ENRICHMENT",
    priority: "P1",
    status: "READY_FOR_REVIEW",
    source: "real_cases/INFRA_ARB_01_BUILDING_HOSPITAL_2026/Case_Facts_Timeline.md",
    sourceType: "precedent",
    targetArea: "src/data/demo-cases/infra-arb-cases.ts",
    summary:
      "Cross-check INFRA_ARB_CASES[] against real_cases/ folder content. Verify: claim amounts match source lex files, timeline events are complete, contradiction entries capture all employer inconsistencies, caseLaw[] have fitScore + action fields, standards[] cite exact clause numbers.",
    reviewGate:
      "Label all output SYNTHETIC / DEMO. No real party names or confidential case details.",
    labCriteria: [
      "Claim amounts match real_cases/ source lex files.",
      "Timeline events include all dates from Case_Facts_Timeline.md.",
      "Each contradiction has severity: 'high' | 'medium' | 'low'.",
      "caseLaw entries have fitScore, status, and action fields.",
      "Standards entries have code, title, keyClause, sourceUrl, confidence.",
    ],
  },
  {
    id: "hearing-tracker-month6",
    title: "Hearing Tracker — next hearing date + countdown widget on Home",
    kind: "ROADMAP",
    priority: "P1",
    status: "READY_FOR_REVIEW",
    source: "ROADMAP.md",
    sourceType: "asset",
    targetArea: "CaseContext.tsx + src/pages/Home.tsx",
    summary:
      "Add nextHearing date field to case data model. Build HearingCountdownWidget. Surface on Home as task-oriented dashboard card alongside Case Strength Snapshot. CaseContext is protected — propose only.",
    reviewGate:
      "Protected file. Apply manually. localStorage fallback must still work after change.",
    labCriteria: [
      "nextHearing field accepted in case data model.",
      "Countdown shows days remaining to next hearing.",
      "Widget shows 'No hearing scheduled' when field is empty.",
      "CaseContext localStorage fallback remains intact.",
    ],
  },
  {
    id: "case-strength-probability-card",
    title: "Case Strength / Probability Assessment Card",
    kind: "ROADMAP",
    priority: "P1",
    status: "READY_FOR_REVIEW",
    source: "ROADMAP.md",
    sourceType: "asset",
    targetArea: "src/components/ — new CaseStrengthCard component",
    summary:
      "Aggregate score: (COURT_SAFE×100 + VERIFIED×70 + SECONDARY×40) / (total×100) × 100. Show as gauge with bands: ≥80 strong, 60–79 moderate, <60 at risk. Disclaimer: 'Research aid — not legal advice.' Surface on Home and case dashboard.",
    reviewGate:
      "Disclaimer must be visible on every render. Score is indicative only.",
    labCriteria: [
      "Formula matches accuracy-rules.md scoring weights.",
      "Disclaimer visible on every render.",
      "Score updates reactively when citation tiers change.",
      "SYNTHETIC / DEMO badge shown in demo mode.",
    ],
  },
  {
    id: "fact-fit-gate-axes-verification",
    title: "Verify Fact-Fit Gate scoring axes in fact_fit_engine.py",
    kind: "STANDARD_REVIEW",
    priority: "P2",
    status: "NEEDS_SOURCE_CHECK",
    source: "ETERNAL_RESEARCH_CHILD/research_findings.log",
    sourceType: "log",
    targetArea: "backend/agents/fact_fit_engine.py",
    summary:
      "Confirm axis weights: incident type 0–40 pts, evidence type 0–35 pts, procedural defect 0–25 pts. Thresholds: ≥70 exact, 50–69 analogous, 30–49 weak, <30 rejected (FATAL_ERROR). Any change must update both Python backend and TypeScript fitLevel mapping consistently.",
    reviewGate:
      "Threshold change requires updating case01-data.ts fitLevel labels simultaneously.",
    labCriteria: [
      "EXACT_THRESHOLD = 70 confirmed in code.",
      "AXIS_INCIDENT_MAX=40, AXIS_EVIDENCE_MAX=35, AXIS_PROCEDURAL_MAX=25.",
      "fitLevel 'rejected' triggers FATAL_ERROR in verification-engine.ts.",
      "Backend unit test covers all 4 threshold bands.",
    ],
  },
  {
    id: "national-beta-launch",
    title: "National Beta Launch — final checklist",
    kind: "ROADMAP",
    priority: "P1",
    status: "READY_FOR_REVIEW",
    source: "ETERNAL_RESEARCH_CHILD/research_findings.log",
    sourceType: "log",
    targetArea: "ROADMAP.md + Netlify + demo video",
    summary:
      "Three unblocked items from Antigravity Logbook: (1) National Beta Launch deployment, (2) 90-second demo video using TC-23 highway arbitration workflow, (3) stress testing with 100MB+ multi-file uploads.",
    reviewGate:
      "Demo video must use TC-23 synthetic data only. SYNTHETIC / DEMO watermark visible throughout.",
    labCriteria: [
      "Netlify production deploy succeeds from clean clone.",
      "Demo video uses only TC-23 synthetic data.",
      "100MB upload test completes without crash.",
      "SYNTHETIC / DEMO watermark visible in video.",
    ],
  },
];
