import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { 
  History, Clock, CheckCircle2, XCircle, Edit3, 
  Download, Copy, Filter, Calendar, AlertTriangle
} from "lucide-react";
import { useCaseContext } from "@/context/CaseContext";
import { apiRequest } from "@/lib/api-client";

interface ChronologyEntry {
  id: string;
  case_id: string;
  date: string | null;
  event: string;
  event_hi: string;
  source_citation: string;
  source_type: string;
  confidence: string;
  needs_review: boolean;
  status: "proposed" | "accepted" | "rejected" | "edited";
  notes?: string;
  is_synthetic: boolean;
}

interface ChronologyResponse {
  case_id: string;
  proposed_at: string;
  total_entries: number;
  entries_needing_date: number;
  entries: ChronologyEntry[];
  disclaimer: string;
}

type FilterType = "all" | "proposed" | "accepted" | "rejected" | "needs_date";

export function ChronologyStudio() {
  const { selectedCase } = useCaseContext();
  const [chronology, setChronology] = useState<ChronologyResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [filter, setFilter] = useState<FilterType>("all");
  const [selectedEntry, setSelectedEntry] = useState<ChronologyEntry | null>(null);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [editForm, setEditForm] = useState({ event: "", event_hi: "", date: "" });
  const [exportFormat, setExportFormat] = useState<"print" | "markdown">("print");

  const caseId = selectedCase?.id || "TC-01";

  const generateChronology = async () => {
    setLoading(true);
    try {
      const response = await apiRequest(`/case/${caseId}/chronology/propose`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ case_id: caseId, include_document_events: true }),
      });
      
      if (!response.ok) {
        throw new Error("Failed to generate chronology");
      }
      
      const data: ChronologyResponse = await response.json();
      setChronology(data);
    } catch (error) {
      console.error("Error generating chronology:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleEntryAction = async (entryId: string, action: "accept" | "reject" | "edit") => {
    try {
      const response = await apiRequest(`/case/${caseId}/chronology/action`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          case_id: caseId,
          entry_id: entryId,
          action,
          ...(action === "edit" ? {
            edited_event: editForm.event,
            edited_event_hi: editForm.event_hi,
            edited_date: editForm.date || null,
          } : {}),
        }),
      });
      
      if (!response.ok) {
        throw new Error("Failed to perform action");
      }
      
      // Refresh chronology
      await generateChronology();
      setEditDialogOpen(false);
    } catch (error) {
      console.error("Error performing action:", error);
    }
  };

  const openEditDialog = (entry: ChronologyEntry) => {
    setSelectedEntry(entry);
    setEditForm({
      event: entry.event,
      event_hi: entry.event_hi,
      date: entry.date || "",
    });
    setEditDialogOpen(true);
  };

  const getFilteredEntries = () => {
    if (!chronology) return [];
    
    return chronology.entries.filter(entry => {
      switch (filter) {
        case "proposed":
          return entry.status === "proposed";
        case "accepted":
          return entry.status === "accepted";
        case "rejected":
          return entry.status === "rejected";
        case "needs_date":
          return entry.date === null;
        default:
          return true;
      }
    });
  };

  const exportChronology = () => {
    if (!chronology) return;
    
    const acceptedEntries = chronology.entries.filter(e => e.status === "accepted");
    
    if (exportFormat === "markdown") {
      const markdown = `# Case Chronology
## ${chronology.case_id}

${chronology.disclaimer}

---

${acceptedEntries.map(entry => `
### ${entry.date || "Date TBD"} - ${entry.event}
**Hindi:** ${entry.event_hi}
**Source:** ${entry.source_citation}
**Confidence:** ${entry.confidence}
${entry.notes ? `**Notes:** ${entry.notes}` : ""}
`).join("\n")}

---
*Generated by Legal Luminaire Chronology Studio*
`;
      
      navigator.clipboard.writeText(markdown);
      alert("Chronology copied to clipboard as Markdown!");
    } else {
      window.print();
    }
  };

  const getConfidenceBadge = (confidence: string) => {
    const colors: Record<string, string> = {
      VERIFIED: "bg-emerald-500/10 text-emerald-700 border-emerald-500/20",
      SECONDARY: "bg-blue-500/10 text-blue-700 border-blue-500/20",
      PENDING: "bg-amber-500/10 text-amber-700 border-amber-500/20",
    };
    return colors[confidence] || colors.PENDING;
  };

  const getStatusBadge = (status: string) => {
    const colors: Record<string, string> = {
      proposed: "bg-gray-500/10 text-gray-700 border-gray-500/20",
      accepted: "bg-emerald-500/10 text-emerald-700 border-emerald-500/20",
      rejected: "bg-red-500/10 text-red-700 border-red-500/20",
      edited: "bg-blue-500/10 text-blue-700 border-blue-500/20",
    };
    return colors[status] || colors.proposed;
  };

  useEffect(() => {
    if (selectedCase) {
      generateChronology();
    }
  }, [selectedCase]);

  if (!chronology && !loading) {
    return (
      <div className="p-6">
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <History className="h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">Chronology Studio</h3>
            <p className="text-sm text-muted-foreground mb-4 text-center">
              Generate a source-cited timeline from your case documents
            </p>
            <Button onClick={generateChronology} disabled={!selectedCase}>
              <Clock className="h-4 w-4 mr-2" />
              Generate Chronology
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="p-6">
        <Card>
          <CardContent className="flex items-center justify-center py-12">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            <p className="ml-4 text-muted-foreground">Generating chronology...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  const filteredEntries = getFilteredEntries();
  const needsDatingCount = chronology?.entries_needing_date || 0;

  return (
    <div className="p-6 space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2">
            <History className="h-6 w-6" />
            Chronology Studio
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            Source-cited timeline generation and review
          </p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setExportFormat("markdown")}
            className={exportFormat === "markdown" ? "bg-primary/10" : ""}
          >
            <Copy className="h-4 w-4 mr-2" />
            Copy as Markdown
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => setExportFormat("print")}
            className={exportFormat === "print" ? "bg-primary/10" : ""}
          >
            <Download className="h-4 w-4 mr-2" />
            Print / Export
          </Button>
          <Button size="sm" onClick={exportChronology}>
            Export
          </Button>
        </div>
      </div>

      {/* Disclaimer */}
      <Card className="bg-amber-50 border-amber-200">
        <CardContent className="py-3">
          <p className="text-sm text-amber-900">
            {chronology?.disclaimer}
          </p>
        </CardContent>
      </Card>

      {/* Stats and Filters */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <Clock className="h-5 w-5 text-primary" />
              <div>
                <p className="text-2xl font-bold">{chronology?.total_entries}</p>
                <p className="text-xs text-muted-foreground">Total Entries</p>
              </div>
            </div>
          </CardContent>
        </Card>
        
        {needsDatingCount > 0 && (
          <Card className="border-amber-300 bg-amber-50">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <AlertTriangle className="h-5 w-5 text-amber-600" />
                <div>
                  <p className="text-2xl font-bold text-amber-900">{needsDatingCount}</p>
                  <p className="text-xs text-amber-700">Needs Dating</p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <CheckCircle2 className="h-5 w-5 text-emerald-500" />
              <div>
                <p className="text-2xl font-bold">
                  {chronology?.entries.filter(e => e.status === "accepted").length}
                </p>
                <p className="text-xs text-muted-foreground">Accepted</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <Filter className="h-5 w-5 text-blue-500" />
              <div className="flex-1">
                <select
                  value={filter}
                  onChange={(e) => setFilter(e.target.value as FilterType)}
                  className="w-full text-sm border rounded-md p-2"
                >
                  <option value="all">All Entries</option>
                  <option value="proposed">Proposed</option>
                  <option value="accepted">Accepted</option>
                  <option value="rejected">Rejected</option>
                  {needsDatingCount > 0 && (
                    <option value="needs_date">Needs Dating</option>
                  )}
                </select>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Needs Dating Lane */}
      {needsDatingCount > 0 && filter === "all" && (
        <Card className="border-amber-300 bg-amber-50">
          <CardHeader>
            <CardTitle className="text-amber-900 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5" />
              Needs Dating Lane
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {chronology?.entries
                .filter(e => e.date === null)
                .map(entry => (
                  <div key={entry.id} className="p-3 bg-white rounded-lg border">
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <p className="font-medium">{entry.event}</p>
                        <p className="text-sm text-muted-foreground">{entry.event_hi}</p>
                        <p className="text-xs text-muted-foreground mt-1">{entry.source_citation}</p>
                      </div>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => openEditDialog(entry)}
                      >
                        <Edit3 className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Chronology Entries */}
      <Card>
        <CardHeader>
          <CardTitle>Timeline Entries</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {filteredEntries.map(entry => (
              <div key={entry.id} className="p-4 border rounded-lg hover:bg-muted/50 transition-colors">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      {entry.date ? (
                        <Badge variant="outline" className="gap-1">
                          <Calendar className="h-3 w-3" />
                          {entry.date}
                        </Badge>
                      ) : (
                        <Badge variant="outline" className="gap-1 text-amber-700 border-amber-300">
                          <AlertTriangle className="h-3 w-3" />
                          Date TBD
                        </Badge>
                      )}
                      <Badge className={getConfidenceBadge(entry.confidence)}>
                        {entry.confidence}
                      </Badge>
                      <Badge className={getStatusBadge(entry.status)}>
                        {entry.status}
                      </Badge>
                    </div>
                    
                    <p className="font-medium text-foreground">{entry.event}</p>
                    <p className="text-sm text-muted-foreground mt-1">{entry.event_hi}</p>
                    
                    <div className="mt-2 text-xs text-muted-foreground">
                      <p><strong>Source:</strong> {entry.source_citation}</p>
                      <p><strong>Type:</strong> {entry.source_type}</p>
                      {entry.notes && <p><strong>Notes:</strong> {entry.notes}</p>}
                    </div>
                  </div>
                  
                  <div className="flex gap-2">
                    {entry.status === "proposed" && (
                      <>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleEntryAction(entry.id, "accept")}
                          className="text-emerald-700 border-emerald-300 hover:bg-emerald-50"
                        >
                          <CheckCircle2 className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleEntryAction(entry.id, "reject")}
                          className="text-red-700 border-red-300 hover:bg-red-50"
                        >
                          <XCircle className="h-4 w-4" />
                        </Button>
                      </>
                    )}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => openEditDialog(entry)}
                    >
                      <Edit3 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Chronology Entry</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium">Event (English)</label>
              <Textarea
                value={editForm.event}
                onChange={(e) => setEditForm({ ...editForm, event: e.target.value })}
                className="mt-1"
              />
            </div>
            <div>
              <label className="text-sm font-medium">Event (Hindi)</label>
              <Textarea
                value={editForm.event_hi}
                onChange={(e) => setEditForm({ ...editForm, event_hi: e.target.value })}
                className="mt-1"
              />
            </div>
            <div>
              <label className="text-sm font-medium">Date (YYYY-MM-DD)</label>
              <Input
                type="date"
                value={editForm.date}
                onChange={(e) => setEditForm({ ...editForm, date: e.target.value })}
                className="mt-1"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={() => selectedEntry && handleEntryAction(selectedEntry.id, "edit")}>
              Save Changes
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}